# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "griffin", github: 'ganmacs/griffin', branch: 'dont-use-SO_REUSEPORT'
gem "grpc_kit"
