# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "griffin", github: 'ganmacs/griffin', branch: 'multi-threads-per-tcp-connetction'
gem "grpc_kit", github: 'ganmacs/grpc_kit', branch: 'multi-threads'
